htm_mall2/htm_mall/urls.py
from django.contrib import admin
from django.urls import path
from htmuser.views import index, RegisterView, LoginView, logout
from product.views import (
    ProductList, ProductCreate, ProductDetail, ProductListAPI, ProductDetailAPI
)
from order.views import OrderCreate, OrderList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('logout/', logout),
    path('register/', RegisterView.as_view()),
    path('login/', LoginView.as_view()),
    path('product/', ProductList.as_view()),
    path('product/create/', ProductCreate.as_view()),
    path('product/<int:pk>/', ProductDetail.as_view()),
    path('order/create/', OrderCreate.as_view()),
    path('order/', OrderList.as_view()),
    path('api/product/', ProductListAPI.as_view()),
    path('api/product/<int:pk>/', ProductDetailAPI.as_view())
]

htm_mall2/product/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=256, verbose_name='상품명')
    price = models.IntegerField(verbose_name='상품가격')
    description = models.TextField(verbose_name='상품설명')
    stock = models.IntegerField(verbose_name='재고')
    register_date = models.DateTimeField(
        auto_now_add=True, verbose_name='등록날짜')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'HTMmall_product'
        verbose_name = '상품'
        verbose_name_plural = '상품'

htm_mall2/product/forms.py
from django import forms
from .models import Product


class RegisterForm(forms.Form):
    name = forms.CharField(
        error_messages={
            'required': '상품명을 입력해주세요'
        },
        max_length=64, label='상품명'
    )
    price = forms.IntegerField(
        error_messages={
            'required': '상품가격을 입력해주세요.'
        }, label='상품가격'
    )
    description = forms.CharField(
        error_messages={
            'required': '상품설명을 입력해주세요.'
        }, label='상품설명'
    )
    stock = forms.IntegerField(
        error_messages={
            'required': '재고를 입력해주세요.'
        }, label='재고'
    )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        price = cleaned_data.get('price')
        description = cleaned_data.get('description')
        stock = cleaned_data.get('stock')

        if not(name and price and description and stock):
            self.add_error('name', '값이 없습니다.')
            self.add_error('price', '값이 없습니다.')

  

htm_mall2/order/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.views.generic.edit import FormView
from django.views.generic import ListView
from .models import Order
from htmuser.decorators import login_required, admin_required
from django.utils.decorators import method_decorator
from django.db import transaction
from product.models import Product
from htmuser.models import HTMuser
# Create your views here.


@method_decorator(login_required, name='dispatch')
class OrderCreate(FormView):
    form_class = RegisterForm
    success_url = '/product/'

    def form_valid(self, form):
        with transaction.atomic():
            pd = Product.objects.get(pk=form.data.get('product'))
            order = Order(
                quantity=form.data.get('quantity'),
                product=pd,
                htmuser=HTMuser.objects.get(
                    email=self.request.session.get('user'))
            )
            order.save()
            pd.stock -= int(form.data.get('quantity'))
            pd.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return redirect('/product/' + str(form.data.get('product')))

    def get_form_kwargs(self, **kwargs):
        kw = super().get_form_kwargs(**kwargs)
        kw.update({
            'request': self.request
        })
        return kw


@method_decorator(login_required, name='dispatch')
class OrderList(ListView):
    template_name = 'order.html'
    context_object_name = 'order_list'

    def get_queryset(self, **kwargs):
        queryset = Order.objects.filter(
            htmuser__email=self.request.session.get('user'))
        return queryset

htm_mall2/product/views.py
from django.views.generic.edit import FormView
from .forms import RegisterForm
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product
from order.forms import RegisterForm as OrderForm
from htmuser.decorators import login_required, admin_required
from django.utils.decorators import method_decorator
from rest_framework import generics
from rest_framework import mixins
from .serializers import ProductSerializer
# Create your views here.


class ProductListAPI(generics.GenericAPIView, mixins.ListModelMixin):
    serializer_class = ProductSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, * args, **kwargs)

    def get_queryset(self):
        return Product.objects.all().order_by('id')


class ProductDetailAPI(generics.GenericAPIView, mixins.RetrieveModelMixin):
    serializer_class = ProductSerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, * args, **kwargs)

    def get_queryset(self):
        return Product.objects.all().order_by('id')


class ProductList(ListView):
    model = Product
    template_name = 'product.html'
    context_object_name = 'product_list'


@method_decorator(admin_required, name='dispatch')
class ProductCreate(FormView):
    template_name = 'register_product.html'
    form_class = RegisterForm
    success_url = '/product/'

    def form_valid(self, form):
        product = Product(
            name=form.data.get('name'),
            price=form.data.get('price'),
            description=form.data.get('description'),
            stock=form.data.get('stock')
        )
        product.save()
        return super().form_valid(form)


class ProductDetail(DetailView):
    template_name = 'product_detail.html'
    queryset = Product.objects.all()
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderForm(self.request)
        return context

htm_mall2/product/templates/product.html
{% extends "base.html" %} {% load humanize %} {% block header %}
<script>
  function product_detail(id) {
    $.ajax({
      url: "/api/product/" + id,
      success: function(result) {
        $("#product-" + id)
          .popover({
            html: true,
            content: result.name + "<br/>" + result.price
          })
          .popover("show");
      }
    });
  }

  function product_leave(id) {
    $("#product-" + id).popover("hide");
  }
  $(document).ready(function() {});
</script>
{% endblock %} {% block contents %}
<div class="row mt-5">
  <div class="col-12">
    <table class="table table-light">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">상품명</th>
          <th scope="col">가격</th>
          <th scope="col">등록날짜</th>
        </tr>
      </thead>
      <tbody class="text-dark">
        {% for product in product_list %}
        <tr>
          <th scope="row">{{ product.id }}</th>
          <th>
            <a
              id="product-{{ product.id }}"
              onmouseenter="product_detail({{ product.id }});"
              onmouseleave="product_leave({{ product.id }});"
              href="/product/{{ product.id }}"
              >{{ product.name }}</a
            >
          </th>
          <th>{{ product.price|intcomma }} 원</th>
          <th>{{ product.register_date|date:'Y-m-d H:i' }}</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

htm_mall2/product/templates/product_detail.html
{% extends "base.html" %} {% load humanize %} {% block contents %}
<div class="row mt-5">
  <div class="col-12">
    <div class="card" style="width: 100%;">
      <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <form method="POST" action="/order/create/">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
              {% ifnotequal field.name 'product' %}
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {% endifnotequal %}
              <input
                type="{{ field.field.widget.input_type }}"
                class="form-control"
                id="{{ field.id_for_label}}"
                placeholder="{{ field.label }}"
                name="{{ field.name }}"
                value = "{% ifequal field.name 'product' %}{{product.id}}{% endifequal %}"
              />
            </div>
            {% if field.errors %}
            <span style="color: red">{{ field.errors }}</span>
            {% endif %} {% endfor %}
            <button type="submit" class="btn btn-primary">주문하기</button>
          </form m>
        </li>
        <li class="list-group-item">가격: {{ product.price|intcomma }} 원</li>
        <li class="list-group-item">
          등록날짜: {{ product.register_date|date:'Y-m-d H:i' }}
        </li>
        <li class="list-group-item">재고: {{ product.stock|intcomma }} 개</li>
        <li class="list-group-item">{{ product.description|safe }}</li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <a href="/product/">목록보기</a>
    </div>
  </div>
  {% endblock %}
</div>

htm_mall2/product/templates/register_product.html
{% extends "base.html" %} {% block header %}
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.css"
  rel="stylesheet"
/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-bs4.js"></script>
<script>
  $(document).ready(function() {
    $("#id_description").summernote({
      height: 300
    });
  });
</script>
{% endblock %} {% block contents %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>상품 생성하기</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    {{ error }}
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <form method="POST" action=".">
      {% csrf_token %} {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% ifequal field.name 'description' %}
        <textarea
          class="form-control"
          name="{{ field.name }}"
          id="{{ field.id_for_label }}"
        ></textarea>
        {% else %}
        <input
          type="{{ field.field.widget.input_type }}"
          class="form-control"
          id="{{ field.id_for_label }}"
          placeholder="{{ field.label }}"
          name="{{ field.name }}"
        />
        {% endifequal %}
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %} {% endfor %}
      <button type="submit" class="btn btn-primary">생성</button>
    </form>
  </div>
</div>
{% endblock %}